In [1]:
import pandas as pd

reviews = pd.read_csv("/Users/kayshahbaaz/Downloads/wine-reviews/winemag-data-130k-v2.csv")

reviews.head()

Unnamed: 0   country                                        description  \
0           0     Italy  Aromas include tropical fruit, broom, brimston...   
1           1  Portugal  This is ripe and fruity, a wine that is smooth...   
2           2        US  Tart and snappy, the flavors of lime flesh and...   
3           3        US  Pineapple rind, lemon pith and orange blossom ...   
4           4        US  Much like the regular bottling from 2012, this...   

                          designation  points  price           province  \
0                        Vulkà Bianco      87    NaN  Sicily & Sardinia   
1                            Avidagos      87   15.0              Douro   
2                                 NaN      87   14.0             Oregon   
3                Reserve Late Harvest      87   13.0           Michigan   
4  Vintner's Reserve Wild Child Block      87   65.0             Oregon   

              region_1           region_2         taster_name  \
0                 Etna                NaN       Kerin O’Keefe   
1                  NaN                NaN          Roger Voss   
2    Willamette Valley  Willamette Valley        Paul Gregutt   
3  Lake Michigan Shore                NaN  Alexander Peartree   
4    Willamette Valley  Willamette Valley        Paul Gregutt   

  taster_twitter_handle                                              title  \
0          @kerinokeefe                  Nicosia 2013 Vulkà Bianco  (Etna)   
1            @vossroger      Quinta dos Avidagos 2011 Avidagos Red (Douro)   
2           @paulgwine       Rainstorm 2013 Pinot Gris (Willamette Valley)   
3                   NaN  St. Julian 2013 Reserve Late Harvest Riesling ...   
4           @paulgwine   Sweet Cheeks 2012 Vintner's Reserve Wild Child...   

          variety               winery  
0     White Blend              Nicosia  
1  Portuguese Red  Quinta dos Avidagos  
2      Pinot Gris            Rainstorm  
3        Riesling           St. Julian  
4      Pinot Noir         Sweet Cheeks

In [3]:
pd.set_option("display.max_rows",5)
reviews

Unnamed: 0   country  \
0                0     Italy   
1                1  Portugal   
...            ...       ...   
129969      129969    France   
129970      129970    France   

                                              description  \
0       Aromas include tropical fruit, broom, brimston...   
1       This is ripe and fruity, a wine that is smooth...   
...                                                   ...   
129969  A dry style of Pinot Gris, this is crisp with ...   
129970  Big, rich and off-dry, this is powered by inte...   

                          designation  points  price           province  \
0                        Vulkà Bianco      87    NaN  Sicily & Sardinia   
1                            Avidagos      87   15.0              Douro   
...                               ...     ...    ...                ...   
129969                            NaN      90   32.0             Alsace   
129970  Lieu-dit Harth Cuvée Caroline      90   21.0             Alsace   

       region_1 region_2    taster_name taster_twitter_handle  \
0          Etna      NaN  Kerin O’Keefe          @kerinokeefe   
1           NaN      NaN     Roger Voss            @vossroger   
...         ...      ...            ...                   ...   
129969   Alsace      NaN     Roger Voss            @vossroger   
129970   Alsace      NaN     Roger Voss            @vossroger   

                                                    title         variety  \
0                       Nicosia 2013 Vulkà Bianco  (Etna)     White Blend   
1           Quinta dos Avidagos 2011 Avidagos Red (Douro)  Portuguese Red   
...                                                   ...             ...   
129969      Domaine Marcel Deiss 2012 Pinot Gris (Alsace)      Pinot Gris   
129970  Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...  Gewürztraminer   

                      winery  
0                    Nicosia  
1        Quinta dos Avidagos  
...                      ...  
129969  Domaine Marcel Deiss  
129970      Domaine Schoffit  

[129971 rows x 14 columns]

In [7]:
reviews.groupby('points').points.count()

points
80     397
81     692
      ... 
99      33
100     19
Name: points, Length: 21, dtype: int64

In [8]:
reviews.groupby('points').price.min()

points
80      5.0
81      5.0
       ... 
99     44.0
100    80.0
Name: price, Length: 21, dtype: float64

In [9]:
reviews.groupby('winery').apply(lambda df: df.title.iloc[0])

winery
1+1=3                          1+1=3 NV Rosé Sparkling (Cava)
10 Knots                 10 Knots 2010 Viognier (Paso Robles)
                                  ...                        
àMaurice    àMaurice 2013 Fred Estate Syrah (Walla Walla V...
Štoka                         Štoka 2009 Izbrani Teran (Kras)
Length: 16757, dtype: object

#### Concept of argmax() and argmin()

In [20]:
import numpy as np

a = np.array([[1,9,7],[2,5,0],[6,3,8]])
a

array([[1, 9, 7],
       [2, 5, 0],
       [6, 3, 8]])

In [21]:
a.argmin()

5

In [22]:
a.argmax()

1

In [23]:
a.flatten()

array([1, 9, 7, 2, 5, 0, 6, 3, 8])

In [24]:
a.argmin(axis=0)

array([0, 2, 1])

In [25]:
a.argmin(axis=1)

array([0, 2, 1])

In [26]:
a.argmax(axis=0)

array([2, 0, 2])

In [27]:
a.argmax(axis=1)

array([1, 1, 2])

In [29]:
reviews.groupby(['country', 'province']).apply(lambda df: df.loc[df.points.argmax()])

/Users/kayshahbaaz/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: FutureWarning: 'argmax' is deprecated. Use 'idxmax' instead. The behavior of 'argmax' will be corrected to return the positional maximum in the future. Use 'series.values.argmax' to get the position of the maximum now.
  """Entry point for launching an IPython kernel.


Unnamed: 0    country  \
country   province                                  
Argentina Mendoza Province       82754  Argentina   
          Other                  78303  Argentina   
...                                ...        ...   
Uruguay   San Jose               39898    Uruguay   
          Uruguay                39361    Uruguay   

                                                                  description  \
country   province                                                              
Argentina Mendoza Province  If the color doesn't tell the full story, the ...   
          Other             Take note, this could be the best wine Colomé ...   
...                                                                       ...   
Uruguay   San Jose          Baked, sweet, heavy aromas turn earthy with ti...   
          Uruguay           Cherry and berry aromas are ripe, healthy and ...   

                                          designation  points  price  \
country   province                                                     
Argentina Mendoza Province           Nicasia Vineyard      97  120.0   
          Other                               Reserva      95   90.0   
...                                               ...     ...    ...   
Uruguay   San Jose           El Preciado Gran Reserva      87   50.0   
          Uruguay           Blend 002 Limited Edition      91   22.0   

                                    province region_1 region_2  \
country   province                                               
Argentina Mendoza Province  Mendoza Province  Mendoza      NaN   
          Other                        Other    Salta      NaN   
...                                      ...      ...      ...   
Uruguay   San Jose                  San Jose      NaN      NaN   
          Uruguay                    Uruguay      NaN      NaN   

                                  taster_name taster_twitter_handle  \
country   province                                                    
Argentina Mendoza Province  Michael Schachner           @wineschach   
          Other             Michael Schachner           @wineschach   
...                                       ...                   ...   
Uruguay   San Jose          Michael Schachner           @wineschach   
          Uruguay           Michael Schachner           @wineschach   

                                                                        title  \
country   province                                                              
Argentina Mendoza Province  Bodega Catena Zapata 2006 Nicasia Vineyard Mal...   
          Other                            Colomé 2010 Reserva Malbec (Salta)   
...                                                                       ...   
Uruguay   San Jose          Castillo Viejo 2005 El Preciado Gran Reserva R...   
          Uruguay           Narbona NV Blend 002 Limited Edition Tannat-Ca...   

                                          variety                winery  
country   province                                                       
Argentina Mendoza Province                 Malbec  Bodega Catena Zapata  
          Other                            Malbec                Colomé  
...                                           ...                   ...  
Uruguay   San Jose                      Red Blend        Castillo Viejo  
          Uruguay           Tannat-Cabernet Franc               Narbona  

[425 rows x 14 columns]

In [30]:
reviews.groupby('country').price.agg([len, min, max])

len   min    max
country                       
Argentina  3800.0   4.0  230.0
Armenia       2.0  14.0   15.0
...           ...   ...    ...
Ukraine      14.0   6.0   13.0
Uruguay     109.0  10.0  130.0

[43 rows x 3 columns]

In [34]:
reviews.groupby('winery').points.agg([len,min,max])

len  min  max
winery                 
1+1=3       6   82   89
10 Knots    4   81   85
...       ...  ...  ...
àMaurice   40   88   94
Štoka       3   88   90

[16757 rows x 3 columns]

In [42]:
reviews.sort_values(by='country')

Unnamed: 0    country  \
90901        90901  Argentina   
122372      122372  Argentina   
...            ...        ...   
129590      129590        NaN   
129900      129900        NaN   

                                              description  \
90901   Odd aromas of bath soap and tropical fruits ar...   
122372  Malty, earthy aromas of cassis and prune are t...   
...                                                   ...   
129590  A blend of 60% Syrah, 30% Cabernet Sauvignon a...   
129900  This wine offers a delightful bouquet of black...   

                       designation  points  price          province region_1  \
90901   Valle Las Acequias Clase A      81    9.0  Mendoza Province  Mendoza   
122372                         NaN      86   15.0  Mendoza Province  Mendoza   
...                            ...     ...    ...               ...      ...   
129590                        Shah      90   30.0               NaN      NaN   
129900                         NaN      91   32.0               NaN      NaN   

       region_2        taster_name taster_twitter_handle  \
90901       NaN  Michael Schachner           @wineschach   
122372      NaN  Michael Schachner           @wineschach   
...         ...                ...                   ...   
129590      NaN      Mike DeSimone        @worldwineguys   
129900      NaN      Mike DeSimone        @worldwineguys   

                                                    title             variety  \
90901   Luis Segundo Correas 2015 Valle Las Acequias C...          Chardonnay   
122372  Bodega Familia Barberis 2010 Cabernet Sauvigno...  Cabernet Sauvignon   
...                                                   ...                 ...   
129590                            Büyülübağ 2012 Shah Red           Red Blend   
129900                                 Psagot 2014 Merlot              Merlot   

                         winery  
90901      Luis Segundo Correas  
122372  Bodega Familia Barberis  
...                         ...  
129590                Büyülübağ  
129900                   Psagot  

[129971 rows x 14 columns]

reference: kaggle.com